SET(GLEW_SEARCH_PATHS
	~/Library/Frameworks
	/Library/Frameworks
	/usr/local
	/usr
	/sw # Fink
	/opt/local # DarwinPorts
	/opt/csw # Blastwave
	/opt
	C:/MinGW
)

FIND_PATH(GLEW_INCLUDE_DIR glew.h
	HINTS
	$ENV{GLEWDIR}
	PATH_SUFFIXES include/GL include
	PATHS ${GLEW_SEARCH_PATHS}
)

FIND_LIBRARY(GLEW_LIBRARY
	NAMES glew GLEW glew32 glew32s libGLEW libGLEW.a
	HINTS
	$ENV{GLEWDIR}
	PATH_SUFFIXES lib64 lib
	PATHS ${GLEW_SEARCH_PATHS}
	DOC "The GLEW library"
)

INCLUDE(FindPackageHandleStandardArgs)

#message(${GLEW_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(glew REQUIRED_VARS GLEW_LIBRARY GLEW_INCLUDE_DIR) 

SET(GLEW_FOUND "NO")
IF(GLEW_LIBRARY AND GLEW_INCLUDE_DIR)
  SET(GLEW_FOUND "YES")
ENDIF(GLEW_LIBRARY AND GLEW_INCLUDE_DIR)