-- test the camera api
local camera = splash_camera.orthoCreate()
assert(camera != nil)
splash_camera.setPosition(camera, 0, 0, 0)
splash_camera.setSize(camera, 800, 600)
splash_camera.setZoom(camera, 12)
splash_camera.setRotation(camera, 0, 0, 0)
splash_camera.translate(camera, 0, 0, 0)
splash_camera.zoom(camera, 0)
splash_camera.rotate(camera, 0, 0, 0)
local pos = splash_camera.getPosition(camera)
local rot = splash_camera.getRotation(camera)
local size = splash_camera.getSize(camera)
local zoom = splash_camera.getZoom(camera)
splash_camera.destorycamera)